### ISSUE TITLE
Having issues on Google assistant responses in my google action. my google action is taking time and the latency is coming 10 seconds. How to handle it

### ISSUE THREAD

**Issue by amiya-elear** [actions-on-google/smart-home-java#13]
Hi Team,

I am doing some video processing, getting a live stream URL, and sending the response, which is taking the time and the latency is coming about 10seconds. How to handle it.

Below is my action Execute code.

```
@/NotNull
@/Override
public ExecuteResponse onExecute(
@/NotNull ExecuteRequest executeRequest, @/Nullable Map<?, ?> map) {
ExecuteResponse.Payload payload = new ExecuteResponse.Payload();

String streamUrl = getstreamurl();
System.out.println("#######HLS Url" + gethslurl);
payload.setCommands(
new ExecuteResponse.Payload.Commands[] {
new ExecuteResponse.Payload.Commands(
new String[] {"5e0f5d1820a57b00113d7a7c"},
"SUCCESS",
new HashMap<String, Object>() {
{
put("cameraStreamAccessUrl", streamUrl);
}
},
null,
null)
});
return new ExecuteResponse(executeRequest.getRequestId(), payload);
}
```

Issue:

Now in my case, after it recognizes the command (typed or spoken) google assistance is not waiting for the response from getstreamurl() function call after 3-5 seconds its automatically sending response"looks like the stream not found", getstreamurl() function call is taking the time and the latency is coming to about 10seconds. How to handle it.

**Comment by Fleker** [comment]
The platform expects a response from the server within about five seconds, otherwise the request will be timed out. If you're experiencing issues, reduce the latency of responses.

**Comment by amiya-elear** [comment]
Thanks, fleker.
Thanks for your answer.one small clarification, Is there any way to handle in google action if my latency is more then 5 seconds, my response will take more then 5 seconds it's for sure. what is the best solution if my server is taking more the 5 seconds to respond.

**Comment by Fleker** [comment]
For a CameraStream command there's really nothing that you can do in the event of high latency.

**Comment by amiya-elear** [comment]
Thanks for your update. Seven out of ten times we see the HLS URL is taking 5.8 sec to 8 sec. This is because we are generating the HLS URL on the fly and sending it via our cloud.
Can we do something using local processing?

**Comment by proppy** [comment]
@amiya-elear did you considered pre-generating the url and/or caching it?

I would suggest we continue this best practice related discussion on a new https://stackoverflow.com/questions/tagged/google-smart-home question, as this project only track issues related to the Java sample.
