### ISSUE TITLE
May I know how to implement for Television? As I didn't find a device type or trails similar to TV.

### ISSUE THREAD

**Issue by littlesohkt** [actions-on-google/smart-home-java#2]

**Comment by devunwired** [comment]
There are already some public feature requests for TV devices and associated traits to be part of the platform. Feel free to track those issues (by adding a +1) and add any additional comments you think would be helpful.

[TV Device Type](https://issuetracker.google.com/issues/139481709)
[Input Mode Trait](https://issuetracker.google.com/issues/136103095)
