### ISSUE TITLE
Someone needs to update instructions and make them easier to follow

### ISSUE THREAD

**Issue by krupis** [actions-on-google/smart-home-java#26]
I have been trying to follow the instructions but find it really difficult because its not well documented and some steps are skipped.

Initially, I got stuck at this point:
![image](https://user-images.githubusercontent.com/22237034/110096587-b9ca0600-7da6-11eb-9f1a-3d3d0154d6c4.png)

I was able to create a service account but there is no option to download json:
![image](https://user-images.githubusercontent.com/22237034/110096728-e7af4a80-7da6-11eb-886f-aa8f73e1b40f.png)

I have then found another guide which shows how to do it properly:
https://developers.google.com/assistant/smarthome/develop/request-sync#java

Next, it is very unclear how to do:
![image](https://user-images.githubusercontent.com/22237034/110096809-00b7fb80-7da7-11eb-844c-df250ca3221a.png)

I have opened firebase console and select cloud firestone:
![image](https://user-images.githubusercontent.com/22237034/110096891-13cacb80-7da7-11eb-8aba-315381e77f15.png)

How do I configure users selection?

**Comment by nalves23** [comment]
I'm having the same problem that you. 
Where did you find the users  configuration on the Cloud Firebase page?

I tried separator "Authentication" but is only to add users to project with email and password. It seems that it isn't the same think.

Suport please.

**Comment by taycaldwell** [comment]
Hi, 

The instructions for this repo have been updated.

Please create a new `users` collection in your Firestore, and add the example entry containing the sample data provided in the README.
