### ISSUE TITLE
Can't resolve types from actions-on-google api

### ISSUE THREAD

**Issue by TheSharpSwan** [actions-on-google/smart-home-java#3]
Hi, 
i'm trying to compile a new project based on this one, which uses actions-on-google 1.7.0 from maven.
I can't solve some types such as
ExecuteRequest.Inputs.Payload.Commands.Execution    (but ExecuteRequest.Inputs exists)
ExecuteResponse.Payload.Commands  (but ExecuteResponse.Payload exists)

Any idea why?

**Comment by Fleker** [comment]
That seems unusual. There's been no changes to the classes in many release cycles, and I had just had built the sample successfully a few days ago. Can you explicitly `import` the class at the top?

**Comment by TheSharpSwan** [comment]
It was an Eclipse Photon problem, I don't understand why but it suggested the needed class import but once added it said it didn't exist.

Tried to clean: eclipse project, clean maven project, clean local maven repository and looking for Eclipse updates. 

Then i installed the 2019-09 version, imported the project and now it works.

Thank you Fleker for you feedback
