### ISSUE TITLE
onExecute handling command OnOff causes Null pointer exception

### ISSUE THREAD

**Issue by murilobaliego** [actions-on-google/smart-home-java#8]
After trying to turn on switch on mobile app the command OnOf handling causes the fault below, any help is welcome.

![command_OnOff_causing_NullPtrException](https://user-images.githubusercontent.com/25311122/83644267-775d6980-a587-11ea-8b6d-b2eec505d72a.png)

**Comment by Fleker** [comment]
Looks like it fails when Firestore tries to lookup the [states.online](https://github.com/actions-on-google/smart-home-java/blob/master/src/main/java/com/example/MyDataStore.java#L199) property in the document. If that doesn't exist, it would throw the NullPointerException.

**Comment by murilobaliego** [comment]
Yes, that is exactly what happens :) thanks. I was using Postman to create the devices. Now I'm using front-end application and the data model is correct.
